prettified
mhoobler/guided-project pull request #1
Opened 2021-02-23 18:36 UTC by mhoobler

#Phase 2 post-review

- [x] Use formatter
  - Used Prettier plugin in VSCode
- [ ] Change redirects to A tags
  - ItemCard & Nav (logo)
- [ ] Move types
- [ ] Move Axios calls
- [ ] Search bar component
- [ ] Stars component

2021-02-23 22:31 UTC, ljmerza requested changes

2021-02-23 22:31 UTC, ljmerza commented on client/src/App.test.tsx
> +type ItemEntry = {
This same type exists somewhere else. Extract to item.type.js file or whatever naming convention you like.

2021-02-23 22:31 UTC, ljmerza commented on client/src/components/ItemCard/index.tsx
>  const ItemCard: React.FC<Props> = (P) => {
capital P? I don't use React typescript but is this common naming scheme? I always use "props".

2021-02-23 22:31 UTC, ljmerza commented on client/src/components/ItemCard/index.tsx
> +    const splitArr = String(P.item.price).split(".");
if you pass in a price arg this function becomes independent of the component and can be pulled into a "utilities" folder for formatting so like `src/utilities/formatting.js`. 

As a side note, you dont have to do this but this can be interpreted as a computationally heavy algorithm so you can `useMemo()` to make sure we dont do all these array computations on every render.

2021-02-23 22:31 UTC, ljmerza commented on client/src/components/ItemCard/index.tsx
> +    if (splitArr[1] && splitArr[1].length === 1) {
`if (splitArr[1]?.length === 1) {`

2021-02-23 22:31 UTC, ljmerza commented on client/src/components/ItemContainer/index.tsx
> +        return <ItemCard key={i} item={e} />;
don't use indexes as keys. use `item._id`. read up on why if you dont know

2021-02-23 22:31 UTC, Maistho reviewed
Hi, left some comments on some stylistic improvements I thought of.

Regarding the PR as a whole, it is quite long, and contains a mix of changes. This makes the PR more difficult to read compared to reading a smaller PR which only changes a single thing.

For example, splitting out all the automatic changes done by prettier to a separate PR would make it a lot easier to what code changes were actually performed here, instead of mixing it up with purely stylistic changes.

2021-02-23 22:31 UTC, Maistho commented on client/src/App.test.tsx
> +};
Instead of defining the type twice, once here and once in `ItemCard/index.ts`, you could export it from `ItemCard/index.ts` and import it here.

2021-02-23 22:31 UTC, Maistho commented on client/src/components/ItemCard/index.tsx
> +        <Ratings rating={P.item.avgRating} />
Good thinking moving this to a separate component :+1:

2021-02-23 22:31 UTC, Maistho commented on client/src/components/ItemContainer/index.tsx
> +import "./style.css";
Same as the previous comment, better to import ItemEntry from somewhere else

2021-02-23 22:31 UTC, Maistho commented on client/src/components/Ratings/index.tsx
> +const Ratings: React.FC<Props> = (P) => {
Tip: I usually deconstruct props right here:

```ts
const Ratings: React.FC<Props> = ({ rating }) => {
```

2021-02-23 22:31 UTC, Maistho commented on client/src/components/Ratings/index.tsx
> +type Props = {
Minor style tip: I usually prefix Prop typenames with the related component, so I would name these props `RatingsProps` to make it more clear what they belong to.

2021-02-23 22:31 UTC, Maistho commented on client/src/pages/Deals.tsx
> +  }, [getSales]);
A nice little cleanup for this part would be to create a custom hook for it instead.

```ts
const useDeals = (): ItemEntry[] => {
  const [itemsList, setItemsList] = useState<ItemEntry[]>([]);
  
  useEffect(() => {
    API.getDeals()
      .then((res) => {
        const { items } = res.data;
        setItemsList(items);
      })
      .catch((err) => console.log(err)); // You probably want some user facing error handling here as well
  }, []); // Empty array here means, only run this once
  
  return itemsList;
};
```

Then you can use it like

```ts
const itemsList = useDeals();
```

2021-02-23 22:31 UTC, Maistho commented on client/src/pages/Deals.tsx
> +  // Should wrap this in useCallback?
If you want to define a function in here, then yes, you need to wrap it in useCallback.

However, since this method is only used inside useEffect, I'd rather just inline it inside useEffect and not define a function beforehand.

2021-02-23 22:33 UTC, ljmerza commented on client/src/pages/Deals.tsx
> +  }, [getSales]);
this isnt a custom hook. this probably ewont be used any where else so dont need to over complicate

2021-02-23 22:43 UTC, Maistho commented on client/src/components/ItemCard/index.tsx
>    const formatPrice = () => {
Depending on what browsers you need to support, you might be able to replace this method with the built-in `Number.prototype.toLocaleString()` instead

```js
price.toLocaleString(
  undefined, // Leave undefined to use the users locale for formatting
  {
    currency: 'USD', // Or whatever currency you're using
    currencyDisplay: 'narrowSymbol',
    style: 'currency'
  },
)
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

2021-02-23 22:46 UTC, Maistho commented on client/src/pages/Deals.tsx
> +  }, [getSales]);
🤷‍♀️

I usually put all my network requests in separate hooks for better separation. What do you mean by "this isn't a custom hook"?

> A custom Hook is a JavaScript function whose name starts with ”use” and that may call other Hooks

https://reactjs.org/docs/hooks-custom.html#extracting-a-custom-hook

2021-02-23 22:57 UTC, ljmerza commented on client/src/pages/Deals.tsx
> +  }, [getSales]);
that's a pretty loose definition but ya got me there i guess.

2021-02-24 00:21 UTC, ljmerza commented on client/src/components/ItemCard/index.tsx
>    const formatPrice = () => {
a combination of this and `.toFixed()` would turn this into a one liner

2021-02-24 19:45 UTC, mhoobler commented on client/src/components/ItemCard/index.tsx
>  const ItemCard: React.FC<Props> = (P) => {
That's just a thing I do with my personal projects, I just like how the P stands out and I feel like it looks a little "tighter". I wouldn't do stuff like that in collaborative projects.

2021-02-24 19:55 UTC, mhoobler commented on client/src/components/Ratings/index.tsx
> +const Ratings: React.FC<Props> = (P) => {
Oh wow I've seen that so many times but never actually done that in my projects lol.

2021-02-24 23:08 UTC, Maistho commented
Overall good changes! :+1_

I don't see why you are passing a string into `useGetItems`. It seems like you should probably pass the params as an object instead, that way you don't have to JSON.stringify/parse and you can also give it a proper type so it is typechecked.


Personally, I somewhat agree that moving the api request into a custom hook is kind of overkill _for now_. If you ever want to use the same list in multiple components/pages or if you want to add more parts (I usually include a bit more information from my request helpers, see example below) then it totally makes sense to have a custom hook.

Example how a bit more advanced custom hook could be made:
```typescript
/** Fetches list of items and returns [loading, items, error] */
export const useItems = (searchString: string): [bool, Item[] | undefined, string | undefined] => {
  // There are probably some advantages to merging these states but I can't be bothered to code it
  const [loading, setLoading] = useState(true)
  const [items, setItems] = useState<Item[] | undefined>(undefined);

  useEffect(() => {
    setLoading(true);
    API.fetchItems(searchString))
      .then((res) => {
        setItems(res.data.items);
      })
      .catch((err) =>{
        setError(err);
      }).finally(() => {
        setLoading(false);
      });
  }, [searchString]);

  return [loading, items, error];
};
```

I would then use it in a component, somewhat like this:
```typescript
export const ItemsList: React.FC<{searchString: string}> = ({ searchString }) => {
  const [loading, items, error] = useItems(searchString);
  
  if (loading) return <p>Loading...</p>;
  
  if (error) return <p className="error">{error}</p>;
  
  return <ul>{items.map((item) => <Item item={item} />)}</ul>;
}

2021-02-25 21:21 UTC, merged